"""Canonical permission catalog for ImpactFlow AI.

Format: <module>:<action>
Actions: create | read | update | delete | manage | export | approve
"""

from __future__ import annotations

PERMISSION_CATALOG: list[dict[str, str]] = [
    # Organizations
    {"code": "organizations:read", "module": "organizations", "action": "read", "description": "View organization profile"},
    {"code": "organizations:update", "module": "organizations", "action": "update", "description": "Update organization profile"},
    {"code": "organizations:manage", "module": "organizations", "action": "manage", "description": "Full organization administration"},
    # Users
    {"code": "users:read", "module": "users", "action": "read", "description": "View users"},
    {"code": "users:create", "module": "users", "action": "create", "description": "Invite users"},
    {"code": "users:update", "module": "users", "action": "update", "description": "Update users"},
    {"code": "users:delete", "module": "users", "action": "delete", "description": "Deactivate/remove users"},
    {"code": "users:manage", "module": "users", "action": "manage", "description": "Full user administration"},
    # Roles
    {"code": "roles:read", "module": "roles", "action": "read", "description": "View roles"},
    {"code": "roles:create", "module": "roles", "action": "create", "description": "Create roles"},
    {"code": "roles:update", "module": "roles", "action": "update", "description": "Update roles"},
    {"code": "roles:delete", "module": "roles", "action": "delete", "description": "Delete roles"},
    {"code": "roles:manage", "module": "roles", "action": "manage", "description": "Full RBAC administration"},
    # Dashboard / Analytics (placeholder for later phases)
    {"code": "dashboard:read", "module": "dashboard", "action": "read", "description": "View dashboards"},
    {"code": "audit:read", "module": "audit", "action": "read", "description": "View audit logs"},
    {"code": "settings:read", "module": "settings", "action": "read", "description": "View settings"},
    {"code": "settings:update", "module": "settings", "action": "update", "description": "Update settings"},
    # Future modules (seeded now for consistency)
    {"code": "programs:read", "module": "programs", "action": "read", "description": "View programs"},
    {"code": "programs:manage", "module": "programs", "action": "manage", "description": "Manage programs"},
    {"code": "projects:read", "module": "projects", "action": "read", "description": "View projects"},
    {"code": "projects:manage", "module": "projects", "action": "manage", "description": "Manage projects"},
    {"code": "activities:read", "module": "activities", "action": "read", "description": "View activities"},
    {"code": "activities:manage", "module": "activities", "action": "manage", "description": "Manage activities"},
    {"code": "work_plans:read", "module": "work_plans", "action": "read", "description": "View work plans"},
    {"code": "work_plans:manage", "module": "work_plans", "action": "manage", "description": "Manage work plans"},
    {"code": "tasks:read", "module": "tasks", "action": "read", "description": "View tasks"},
    {"code": "tasks:manage", "module": "tasks", "action": "manage", "description": "Manage tasks"},
    {"code": "grants:read", "module": "grants", "action": "read", "description": "View grants"},
    {"code": "grants:manage", "module": "grants", "action": "manage", "description": "Manage grants"},
    {"code": "donors:read", "module": "donors", "action": "read", "description": "View donors"},
    {"code": "donors:manage", "module": "donors", "action": "manage", "description": "Manage donors"},
    {"code": "budgets:read", "module": "budgets", "action": "read", "description": "View budgets"},
    {"code": "budgets:manage", "module": "budgets", "action": "manage", "description": "Manage budgets"},
    {"code": "beneficiaries:read", "module": "beneficiaries", "action": "read", "description": "View beneficiaries"},
    {"code": "beneficiaries:manage", "module": "beneficiaries", "action": "manage", "description": "Manage beneficiaries"},
    {"code": "communities:read", "module": "communities", "action": "read", "description": "View communities"},
    {"code": "communities:manage", "module": "communities", "action": "manage", "description": "Manage communities"},
    {"code": "households:read", "module": "households", "action": "read", "description": "View households"},
    {"code": "households:manage", "module": "households", "action": "manage", "description": "Manage households"},
    {"code": "theories_of_change:read", "module": "theories_of_change", "action": "read", "description": "View theories of change"},
    {"code": "theories_of_change:manage", "module": "theories_of_change", "action": "manage", "description": "Manage theories of change"},
    {"code": "logframes:read", "module": "logframes", "action": "read", "description": "View logframes"},
    {"code": "logframes:manage", "module": "logframes", "action": "manage", "description": "Manage logframes"},
    {"code": "indicators:read", "module": "indicators", "action": "read", "description": "View indicators"},
    {"code": "indicators:manage", "module": "indicators", "action": "manage", "description": "Manage indicators"},
    {"code": "monitoring:read", "module": "monitoring", "action": "read", "description": "View monitoring results"},
    {"code": "monitoring:manage", "module": "monitoring", "action": "manage", "description": "Manage monitoring results"},
    {"code": "evaluations:read", "module": "evaluations", "action": "read", "description": "View evaluations"},
    {"code": "evaluations:manage", "module": "evaluations", "action": "manage", "description": "Manage evaluations"},
    {"code": "surveys:read", "module": "surveys", "action": "read", "description": "View surveys"},
    {"code": "surveys:manage", "module": "surveys", "action": "manage", "description": "Manage surveys"},
    {"code": "surveys:submit", "module": "surveys", "action": "submit", "description": "Submit survey / form responses"},
    {"code": "reports:read", "module": "reports", "action": "read", "description": "View reports"},
    {"code": "reports:export", "module": "reports", "action": "export", "description": "Export reports"},
    {"code": "reports:manage", "module": "reports", "action": "manage", "description": "Manage reports"},
    {"code": "dashboards:manage", "module": "dashboards", "action": "manage", "description": "Manage saved dashboards"},
    {"code": "analytics:read", "module": "analytics", "action": "read", "description": "View analytics"},
    {"code": "maps:read", "module": "maps", "action": "read", "description": "View map layers"},
    {"code": "maps:manage", "module": "maps", "action": "manage", "description": "Manage map layers"},
    {"code": "evidence:read", "module": "evidence", "action": "read", "description": "View evidence"},
    {"code": "evidence:manage", "module": "evidence", "action": "manage", "description": "Manage evidence"},
    {"code": "finance:read", "module": "finance", "action": "read", "description": "View finance"},
    {"code": "finance:manage", "module": "finance", "action": "manage", "description": "Manage finance"},
    {"code": "ai:use", "module": "ai", "action": "use", "description": "Use AI Copilot features"},
    {"code": "predictions:read", "module": "predictions", "action": "read", "description": "View AI predictions"},
    {"code": "predictions:manage", "module": "predictions", "action": "manage", "description": "Manage AI predictions"},
    {"code": "narratives:read", "module": "narratives", "action": "read", "description": "View AI narratives"},
    {"code": "narratives:manage", "module": "narratives", "action": "manage", "description": "Manage AI narratives"},
    {"code": "knowledge:read", "module": "knowledge", "action": "read", "description": "View knowledge base"},
    {"code": "knowledge:manage", "module": "knowledge", "action": "manage", "description": "Manage knowledge base"},
    {"code": "marketplace:read", "module": "marketplace", "action": "read", "description": "Browse marketplace apps"},
    {"code": "marketplace:manage", "module": "marketplace", "action": "manage", "description": "Install marketplace apps"},
    {"code": "integrations:read", "module": "integrations", "action": "read", "description": "View integrations"},
    {"code": "integrations:manage", "module": "integrations", "action": "manage", "description": "Manage integrations"},
    {"code": "api_keys:read", "module": "api_keys", "action": "read", "description": "View API keys"},
    {"code": "api_keys:manage", "module": "api_keys", "action": "manage", "description": "Manage API keys"},
    {"code": "branding:read", "module": "branding", "action": "read", "description": "View white-label branding"},
    {"code": "branding:manage", "module": "branding", "action": "manage", "description": "Manage white-label branding"},
    {"code": "workflows:read", "module": "workflows", "action": "read", "description": "View workflows, runs, and approvals"},
    {"code": "workflows:manage", "module": "workflows", "action": "manage", "description": "Create and manage workflows"},
    {"code": "workflows:approve", "module": "workflows", "action": "approve", "description": "Decide workflow approvals"},
    {"code": "sync:push", "module": "sync", "action": "push", "description": "Push offline changes from field devices"},
    {"code": "sync:pull", "module": "sync", "action": "pull", "description": "Pull delta updates to field devices"},
    {"code": "devices:register", "module": "devices", "action": "register", "description": "Register field devices"},
    {"code": "devices:read", "module": "devices", "action": "read", "description": "View registered field devices"},
    {"code": "devices:manage", "module": "devices", "action": "manage", "description": "Manage and revoke field devices"},
]

# Default system roles and their permission codes
SYSTEM_ROLES: dict[str, dict] = {
    "org_admin": {
        "name": "Organization Admin",
        "description": "Full access within the organization",
        "permissions": [p["code"] for p in PERMISSION_CATALOG],
    },
    "manager": {
        "name": "Program Manager",
        "description": "Manage programs, projects, and reporting",
        "permissions": [
            "organizations:read",
            "users:read",
            "roles:read",
            "dashboard:read",
            "settings:read",
            "programs:read",
            "programs:manage",
            "projects:read",
            "projects:manage",
            "activities:read",
            "activities:manage",
            "work_plans:read",
            "work_plans:manage",
            "tasks:read",
            "tasks:manage",
            "grants:read",
            "grants:manage",
            "donors:read",
            "donors:manage",
            "budgets:read",
            "budgets:manage",
            "beneficiaries:read",
            "beneficiaries:manage",
            "communities:read",
            "communities:manage",
            "households:read",
            "households:manage",
            "theories_of_change:read",
            "theories_of_change:manage",
            "logframes:read",
            "logframes:manage",
            "indicators:read",
            "indicators:manage",
            "monitoring:read",
            "monitoring:manage",
            "evaluations:read",
            "evaluations:manage",
            "surveys:read",
            "surveys:manage",
            "surveys:submit",
            "reports:read",
            "reports:export",
            "reports:manage",
            "dashboards:manage",
            "analytics:read",
            "maps:read",
            "maps:manage",
            "evidence:read",
            "evidence:manage",
            "finance:read",
            "finance:manage",
            "ai:use",
            "predictions:read",
            "predictions:manage",
            "narratives:read",
            "narratives:manage",
            "knowledge:read",
            "knowledge:manage",
            "marketplace:read",
            "marketplace:manage",
            "integrations:read",
            "integrations:manage",
            "api_keys:read",
            "api_keys:manage",
            "branding:read",
            "branding:manage",
            "workflows:read",
            "workflows:manage",
            "workflows:approve",
        ],
    },
    "meal_officer": {
        "name": "MEAL Officer",
        "description": "Monitoring, evaluation, and learning",
        "permissions": [
            "organizations:read",
            "dashboard:read",
            "programs:read",
            "projects:read",
            "activities:read",
            "work_plans:read",
            "tasks:read",
            "grants:read",
            "donors:read",
            "budgets:read",
            "finance:read",
            "beneficiaries:read",
            "communities:read",
            "households:read",
            "theories_of_change:read",
            "theories_of_change:manage",
            "logframes:read",
            "logframes:manage",
            "indicators:read",
            "indicators:manage",
            "monitoring:read",
            "monitoring:manage",
            "evaluations:read",
            "evaluations:manage",
            "surveys:read",
            "surveys:manage",
            "surveys:submit",
            "reports:read",
            "reports:export",
            "reports:manage",
            "dashboards:manage",
            "analytics:read",
            "maps:read",
            "maps:manage",
            "evidence:read",
            "evidence:manage",
            "ai:use",
            "predictions:read",
            "predictions:manage",
            "narratives:read",
            "narratives:manage",
            "knowledge:read",
            "knowledge:manage",
            "marketplace:read",
            "integrations:read",
            "workflows:read",
            "workflows:approve",
        ],
    },
    "field_officer": {
        "name": "Field Officer",
        "description": "Field data collection and beneficiary registration",
        "permissions": [
            "dashboard:read",
            "projects:read",
            "activities:read",
            "tasks:read",
            "tasks:manage",
            "beneficiaries:read",
            "beneficiaries:manage",
            "communities:read",
            "communities:manage",
            "households:read",
            "households:manage",
            "indicators:read",
            "monitoring:read",
            "monitoring:manage",
            "surveys:read",
            "surveys:manage",
            "surveys:submit",
            "evidence:read",
            "evidence:manage",
            "maps:read",
            "workflows:read",
            "sync:push",
            "sync:pull",
            "devices:register",
        ],
    },
    "viewer": {
        "name": "Viewer",
        "description": "Read-only access",
        "permissions": [
            "organizations:read",
            "dashboard:read",
            "programs:read",
            "projects:read",
            "activities:read",
            "work_plans:read",
            "tasks:read",
            "grants:read",
            "donors:read",
            "budgets:read",
            "beneficiaries:read",
            "communities:read",
            "households:read",
            "theories_of_change:read",
            "logframes:read",
            "indicators:read",
            "monitoring:read",
            "evaluations:read",
            "surveys:read",
            "reports:read",
            "analytics:read",
            "maps:read",
            "evidence:read",
            "finance:read",
            "predictions:read",
            "narratives:read",
            "knowledge:read",
            "marketplace:read",
            "integrations:read",
            "workflows:read",
        ],
        "is_default": True,
    },
}
